### ISSUE TITLE
got build error

### ISSUE THREAD

**Issue by ccc7574** [AnyaCoder/fish-speech-gui#4]
got the error during build:

Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Requirement already satisfied: pywin32 in c:\users\qkkkwa\appdata\local\anaconda3\envs\pyqt\lib\site-packages (308)
Requirement already satisfied: cffi in c:\users\qkkkwa\appdata\local\anaconda3\envs\pyqt\lib\site-packages (1.17.1)
Requirement already satisfied: pycparser in c:\users\qkkkwa\appdata\local\anaconda3\envs\pyqt\lib\site-packages (from cffi) (2.22)
Nuitka-Options: Used command line options: --standalone --output-dir=dist --follow-import-to=fish main.py --onefile --output-filename=fish --include-data-dir=assets=assets
Nuitka-Options: --include-data-dir=locales=locales --include-data-files=fish_audio_preprocess=fish_audio_preprocess/=**/*.py --windows-console-mode=disable --enable-plugins=pkg-resources
Nuitka-Options: --enable-plugins=pyqt6 --nofollow-import-to=mkl,click,scipy,pandas,matplotlib,pytest --include-qt-plugins=sensible,multimedia --show-memory --show-progress
Nuitka-Options: --windows-icon-from-ico=assets/favicon.ico

**FATAL: Error, 'fish_audio_preprocess' does not match any files.**

**Comment by AnyaCoder** [comment]
Oh, I forgot this...
You can firstly clone this repository by this command: 
`git clone https://github.com/AnyaCoder/audio-preprocess`
Then copy the folder `fish-audio-preprocess` to the root of `fish-speech-gui` repository.

**Comment by ericfarng** [comment]
for the next person, Is it possible to update the instructions? or add this directory into this repo? I'm happy to do it, just tell me which you want.

**Comment by AnyaCoder** [comment]
> for the next person, Is it possible to update the instructions? or add this directory into this repo? I'm happy to do it, just tell me which you want.

Yes, I think i need to add the folder, thanks for reminding me :)
